{% set version = '1.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-elasticnet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/elasticnet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/elasticnet/elasticnet_{{ version }}.tar.gz
  sha256: abde7cd63a3057169bad154de5d2185281f6325f4e19ea84261f89ab2dbd2d5d

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-lars
  run:
    - r-base
    - r-lars

test:
  commands:
    - $R -e "library('elasticnet')"           # [not win]
    - "\"%R%\" -e \"library('elasticnet')\""  # [win]

about:
  home: http://www.stat.umn.edu/~hzou
  license: GPL (>= 2)
  summary: 'Provides functions for fitting the entire solution path of the Elastic-Net and also
    provides functions for estimating sparse Principal Components. The Lasso solution
    paths can be computed by the same function. First version: 2005-10.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: elasticnet
# Version: 1.1.1
# Date: 2012-06-25
# Title: Elastic-Net for Sparse Estimation and Sparse PCA
# Author: Hui Zou <hzou@stat.umn.edu> and Trevor Hastie <hastie@stanford.edu>
# Maintainer: Hui Zou <hzou@stat.umn.edu>
# Depends: R (>= 2.10), lars
# Description: Provides functions for fitting the entire solution path of the Elastic-Net and also provides functions for estimating sparse Principal Components. The Lasso solution paths can be computed by the same function. First version: 2005-10.
# License: GPL (>= 2)
# URL: http://www.stat.umn.edu/~hzou
# Packaged: 2018-08-31 16:20:18 UTC; hornik
# Repository: CRAN
# Date/Publication: 2018-08-31 17:40:01 UTC
# NeedsCompilation: no
