travis:
  secure:
    BINSTAR_TOKEN: JdhgqbgExzOQS6ZhPBzybOQEdaMaTvdnFKFf5DGNiKAV94RXczAgpDY6UrRA2qYXRDvpeyJ2zM3p71utuL5rKIqHr8dE2gQk4oWchtMciollLVCf/QB6NmqRBjhNXV5CZgCS+JtIosERqCQ81a702l078tBBKQ6MTDR15zdljDEbrbLm/K2TnmGc/BDpOlP+6NAndndRdcq9kEwZgCJO2W+FqsiNxD17FEYbe4MP/AXjQX2TlMVT8t/2KuwvJRCkCkIMaQ/IZOmHRzLXKje3zDNmQipgn/MBe9dqiv1Lyi0tADtjHxtOjeZFyWnjjSVr0DWNKsy0N2qn9xeyxQIARNGkkOixP2yUspKaXd6O5kFjWdvrECV1HFVPXkAXGpu3wHdlkUJsFSS7LtpNPTDzzUH25neXWOBy69A8UyZRdgE0u7AFTh/BQvVZ2KS0+1ucKdByVemJj1KyQGlxchyZLB5QKyqfD1fqcr+rQkbPm7rRdY6RvIzT3Bs57QFo301XSkVAaRuTJKPIgIq6g12+CvIeVNPKS8sc3J3snoCWd7/RGjl3gx0OQyvj85+1FZbp6WDoEFidGYS96nd6XotVawMralh52Q0/fkat7gr0LAN91jChOZ15K+2rl5fLwszbQWnz1XdrXHb5kC6CZ9PWV1rdyqfJRvxnGjlHY8Tv63g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
