appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: s+QDM/bE0BSkNIckgmfKcd1stzibjHfwFMt4yADskYV+mEJtG4et2qnaeT3oFjHJUTuow8Ef7rY/PFbuHWeq5dHn9EYpUuY4Qjw7b0IPKQLZcadAi/tIglVmkkOzl1170lwVL4wM8HJoihAlOHtql4h0ugcFzaFyPSQxJACCqeBht8QvHmQ1nNfPFB2OyMOwf7wBCgGPbTXgD+NYiTTtBYgk81rP/0MHY3QGkuKHcWCqt7bmyETtGmcFtyofDnm8IFE88x9yG9iUziY4xc4jQQ8XtSyEnqg40kLVGK5oQaFlCqP8WDQtlaD/RuFWy6qy6D9IJceEu6mQF24WTNi9Wj9F8q757ADqm1iEKl8oqRKyegjTLWyQ2BNw8uVmuVmI/fqhntisxQJowVV0cG/scts4pZ4QSOIRYr0oE0eNEoaMYKqDKCAtLu/qg4PwMTIWmvm6YggctGEqbAMZ3V2hntHo7x4TbhvzW79jUZvMXUDi/XB3Ah1WLvYRIO+AuO33OX5fzikNmlYJpsQJCvxiIVzdA/iX2Kbsm/jCV/JfNspS8dTzp7F6B7PuQMr2sDqTS5gei/1qeh1HPDdKMNTxgdlsoterXe89hm56jooZcsQqYgysb59Kwb/HRDdNdrrKxNGJLxKUL73fbuTpGIA/vlb3zJS3fIQ4ekGW/arRf1k=}
bot:
  automerge: true
